// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNg54FjsddZ55_LwJhasaMJ7bLplg76F8',
    appId: '1:439061140143:web:9e4c0add8e233a6cb73a5a',
    messagingSenderId: '439061140143',
    projectId: 'mis-gastos-jb',
    authDomain: 'mis-gastos-jb.firebaseapp.com',
    storageBucket: 'mis-gastos-jb.appspot.com',
    measurementId: 'G-37PYQVGR58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAJdborolaw2jQI8Rr4lNBv8cy0kUVd20',
    appId: '1:439061140143:android:7c2487318e693cfcb73a5a',
    messagingSenderId: '439061140143',
    projectId: 'mis-gastos-jb',
    storageBucket: 'mis-gastos-jb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc82k95ch3lHIW1qdSSSmCoKK1T_UivWw',
    appId: '1:439061140143:ios:d548c0f3d604517db73a5a',
    messagingSenderId: '439061140143',
    projectId: 'mis-gastos-jb',
    storageBucket: 'mis-gastos-jb.appspot.com',
    iosClientId: '439061140143-mugcaiu084d3o1vers34dlh19h938eb6.apps.googleusercontent.com',
    iosBundleId: 'com.jb.misgastos.misGastos',
  );
}
